[package]
name = "rustfromc"
version = "0.1.0"
edition = "2021"

[lib]
crate-type =["cdylib"]

[dependencies]
cbindgen = { version = "0.26.0", default-features = false }

[build-dependencies]
cbindgen = { version = "0.26.0", default-features = false }